### ISSUE TITLE
tileLocalEachLayer variable description

### ISSUE THREAD

**Issue by waawaachi** [neurosim/DNN_NeuroSim_V1.2#1]
Hello, I am very interested in this wonderful neurosim ppa simulator code.
I've reviewed this code since version 1.0 with your several papers.
But, I can not find some functions and variables anywhere.
So here is my question.

Would you please tell me what is the meaning of tileLocalEachLayer and what is the role?

Thanks

**Comment by neurosim** [comment]
Hello, thanks for your interest!

So "tileLocalEachLayer" was originally defined as the location of the tile or the last tile (if there are multiple tiles for one layer) for each layer, it was assumed to be used for "leaf-to-leaf" communication among tiles, to detect the travel distance of the data.
While currently our floorplan assumed the activation will all go back to global buffer and be sent back to next layer (other tiles), so now we only have "root-to-leaf" data flow, the travel distance is always same in H-tree.
We keep the "tileLocalEachLayer" for future versions with different data flow.

Thanks!

**Comment by waawaachi** [comment]
Thanks for your kind reply.
So, tileLocalEachLayer has no effect on PPA in this version.
Since, the first and second input arguments of HTree::CalculateLatency/Power  are always "0", you set.

Thanks.
