### ISSUE TITLE
Overlapping create some objects in Chip.cpp

### ISSUE THREAD

**Issue by waawaachi** [neurosim/DNN_NeuroSim_V1.2#2]
Hello,
I'm so confused, "saInPE" is created in HTInitialize and then, PEInitialize creates "sa" object again with "saInPE" reference.
I got same PPA results after deleting the "saInPE" creating code in HTInitialize.
Would you please tell me your intention about it.

Also, here is very similar question.
With param->novelMapping true configuration, in ChipInitialize funciton, it calls HTInitialize funciton twice with different number of PE and desiredPESize, copy the code below.

/*** Initialize Tile ***/
if (param->novelMapping) {
	TileInitialize(inputParameter, tech, cell, numPENM, desiredPESizeNM);
}
TileInitialize(inputParameter, tech, cell, ceil((double)(desiredTileSizeCM)/(double)(desiredPESizeCM)), desiredPESizeCM);

Because of overlapping, the tile must be initialized by only second call, which represents "conventional mapping" value for num and size of PE.
As I understand, initialized variable in sub-initialization-function of ChipInitialize will be used in sub-performance calculation-function of ChipCalculatePerformance. 
In "novel mapping" case, however, it would use some parameters for "conventional mapping" like as numAdderTree variable.

I think the different mapping tiles object should be created respectively, to calculate performance correctly.
Please check if I'm correct or not.

Thanks.

**Comment by neurosim** [comment]
Hello,
Yes, you are right, and we have update the codes and defined the tile separately, thanks very much!

**Comment by waawaachi** [comment]
Thank you...for your fast update.
