### ISSUE TITLE
operation number of accumulation.

### ISSUE THREAD

**Issue by waawaachi** [neurosim/DNN_NeuroSim_V1.2#3]
In chip.cpp, the output of pe can be accumulated by accumulationCM object.
I wonder how it consider the number of access of the accumulator. 
I think, the variable numInVector and the peSize should be used to calculate the access number of accumulation and then it should be multiplied to the accumulation’s read latency.

I copied the related code below.

accumulationCM->CalculateLatency(param->numColMuxed, ceil((double)weightMatrixRow/(double)peSize), 0);

thanks a lot!

**Comment by neurosim** [comment]
Hi, I believe you are talking about the tile.cpp file, and you are right, we should consider the numInVector into the number of operations, we have updated the tile.cpp accordingly. Thanks!

**Comment by waawaachi** [comment]
Thank you so much.
