### ISSUE TITLE
Question about the Buffer and DFF clock frequency.

### ISSUE THREAD

**Issue by waawaachi** [neurosim/DNN_NeuroSim_V1.2#4]
Hi, I have a simple question.
Would you please tell me the reason for double clk frequency of DFF in DFF.cpp and DFF in Buffer.cpp during calculating their latency.
I copied the related code below.

In DFF.cpp
readLatency += 1/clkFreq/2;

In Buffer.cpp
readWholeLatency += ((double) 1/clkFreq/2)*((double) numBit/interface_width);  // assume dff need half clock cycle to access

Further, you may consider the double clock frequency in SRAM cases of Buffer.cpp.
But, I can't figure out what part of code represent it. 
Could you please point what is the related.
I also copied the SRAM latency calculating code below.

		if (SRAM) {
			wlDecoder.CalculateLatency(1e20, lengthRow * 0.2e-15/1e-6, NULL, (double) numBit/interface_width, (double) numBit/interface_width);
			precharger.CalculateLatency(1e20, lengthCol * 0.2e-15/1e-6, (double) numBit/interface_width, (double) numBit/interface_width);
			sramWriteDriver.CalculateLatency(1e20, lengthCol * 0.2e-15/1e-6, lengthCol * unitWireRes, (double) numBit/interface_width);
			
			double resCellAccess = CalculateOnResistance(param->widthAccessCMOS * tech.featureSize, NMOS, inputParameter.temperature, tech);
			double capCellAccess = CalculateDrainCap(param->widthAccessCMOS * tech.featureSize, NMOS, param->widthInFeatureSizeSRAM * tech.featureSize, tech);
			double resPullDown = CalculateOnResistance(param->widthSRAMCellNMOS * tech.featureSize, NMOS, inputParameter.temperature, tech);
			double tau = (resCellAccess + resPullDown) * (capCellAccess + lengthCol * 0.2e-15/1e-6) + lengthCol * unitWireRes * (lengthCol * 0.2e-15/1e-6) / 2;
			tau *= log(tech.vdd / (tech.vdd - param->minSenseVoltage / 2));   
			double gm = CalculateTransconductance(param->widthAccessCMOS * tech.featureSize, NMOS, tech);
			double beta = 1 / (resPullDown * gm);
			double colRamp = 0;
			colDelay = horowitz(tau, beta, wlDecoder.rampOutput, &colRamp)*((double) numBit/interface_width);
			readWholeLatency += wlDecoder.readLatency + precharger.readLatency + colDelay;
			writeWholeLatency += wlDecoder.writeLatency + precharger.writeLatency + sramWriteDriver.writeLatency;
		}

**Comment by neurosim** [comment]
Hi, for DFF circuits, we assume it operates with the clock and is triggered by clock edges, thus the latency for single operation is assumed as half clock cycle.
While for SRAM-based buffer, we have the peripheral circuits to access the memory, so we do not use the half clock cycle anymore.
